### ISSUE TITLE
Intervals tab - Pace 

### ISSUE THREAD

**Issue by rilling** [rilling/OpenTracks-Concordia#231] opened 2023-02-07 20:39 UTC
**Describe the bug**
Pace should be Average Moving Pace and not Average Pace. 
Currently the Average Pace for the intervals are displayed, but it should display the Moving Pace for the interval.

**To Reproduce**
Stat screen shows AVG Moving Pace: 10:04 min/km  and  AVG pace: 10.21 min/km
![Screenshot_20230207-153237](https://user-images.githubusercontent.com/1248571/217359470-dd04d580-3b26-4650-82b9-46a6c56629e5.png)

Change column header to AVG Moving Pace + stats should display the AVG moving Pace per interval
![Screenshot_20230207-153256](https://user-images.githubusercontent.com/1248571/217359545-f8f5e9e4-61a5-429d-b01c-7228b4394b5c.png)

**Technical information**

**Comment by bajwa96** [comment] 2023-03-16 00:04
Started analyzing the issue

**Comment by bajwa96** [comment] 2023-03-16 00:50
Merge request could be found at https://github.com/rilling/OpenTracks-Concordia/pull/244

**Comment by AYYANARK** [comment] 2023-03-18 02:25
@bajwa96 Let me test the code and confirm whether it is working perfectly

**Comment by AYYANARK** [comment] 2023-03-19 11:33
The code change performed to achieve the enhancement is working fine and I have tested it from my end. Good to close.

**Comment by Driven2Develop** [comment] 2023-03-19 16:58
The issue will be assigned to @VigneshP1505 @riddhibhuva

**Comment by Driven2Develop** [comment] 2023-03-19 18:21
Hello @AYYANARK have you integrated the changes necessary to close this issue since it still remains open? 

Can you share with me the commits/changes that were done to address the issue?

Thanks, 
Iymen A.

**Comment by AYYANARK** [comment] 2023-03-19 23:20
Please find the merge request by bajwa96 in the same thread.

**Comment by mit-27** [comment] 2023-03-19 23:24
I have verified the required changes that were implemented by @bajwa96  and @karmakarvishal. The implemented changes successfully resolved the open issue. Below I am attaching the screenshot of the application that I run on my local machine.

![image](https://user-images.githubusercontent.com/63452683/226216267-0c94ee0d-dd9b-40d5-9cad-f9536bd10230.png)

**Comment by karansingla007** [comment] 2023-03-20 00:52
<img width="1188" alt="image" src="https://user-images.githubusercontent.com/26064126/226222110-9ffef51b-e324-4395-9ad1-ad99f558c6b6.png">

I confirm that the modifications made by @bajwa96 and @karmakarvishal  have been checked and have effectively addressed the previously reported problem. I am also including a screenshot of the application that I tested on my personal computer.

**Comment by SiddharthOza00** [comment] 2023-03-20 02:50
After careful examination of the changes made by @bajwa96 and @karmakarvishal, I can confirm that the reported issue has been effectively addressed. Along with this confirmation, I am including a screenshot of the application that I personally tested on my computer.
<img width="1292" alt="Screenshot 2023-03-19 at 9 17 14 PM" src="https://user-images.githubusercontent.com/55457720/226235502-577d5f0e-a2ae-43b8-8890-69a604a43054.png">

**Comment by VigneshP1505** [comment] 2023-03-20 02:57
I have examined the changes on my side. Working as expected.
![sshot](https://user-images.githubusercontent.com/59405012/226236260-c12a96fa-3c8e-479b-989d-2cb3e2fc15fe.png)

**Closed by VigneshP1505** 2023-03-20 02:57 UTC
Labels: enhancement, G#6

**Comment by riddhibhuva** [comment] 2023-03-20 03:15
examined the changes on my side after the update. Works fine. Putting up the before and after images.
<img width="1440" alt="Screenshot 2023-03-19 at 11 13 21 PM" src="https://user-images.githubusercontent.com/70747205/226238264-998436e8-58f0-4a04-ab37-288bcf2ed897.png">
<img width="1440" alt="Screenshot 2023-03-19 at 11 13 21 PM" src="https://user-images.githubusercontent.com/70747205/226238345-8589a628-701d-42a2-a33b-b855624afb56.png">
